#!/bin/bash

export PACKAGE_CORE_NAME="monitoror"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v4.0.1
export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/monitoror/monitoror/releases/download"
